version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: deck.gl
    versions:
    - 8.3.15
    - 8.4.0
    - 8.4.1
    - 8.4.10
    - 8.4.11
    - 8.4.12
    - 8.4.2
    - 8.4.3
    - 8.4.5
    - 8.4.6
    - 8.4.7
    - 8.4.8
    - 8.4.9
  - dependency-name: d3-scale
    versions:
    - 3.2.3
    - 3.2.4
  - dependency-name: react-map-gl
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.10
    - 6.1.11
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.1.9
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
